# Generated by Django 4.1.4 on 2022-12-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
